### PR TITLE
Remove Fedora from default boot menu

### PR DESCRIPTION
**Pull request by malex984**
* fix typo in `/boot/grub/grub.cfg` 
* removed Fedora from default boot menu

### CODE REVIEW

**Comment by porst17** [comment]
Why do you want to remove Fedora 26 from the list? It is part of the download script just like most of the other ISO files and it is also a good example of a configuration that does not provide a `loopback.cfg` for `grub` (like Ubuntu does).

**Comment by malex984** [comment]
I have just commented it out so that it is not be accessible by *default*

**Comment by porst17** [comment]
Ok, I will merge it. But I asked you *why* you want to hide it and your last comment doesn't contain an argument.

**Comment by malex984** [comment]
well, usually Fedora 26 is not part of multi-boot USB drives related to IMAGINARY OS, thus it should not be *accessible* via the *default* boot menu... no?

**Comment by porst17** [comment]
The other entries besides the new IMAGINARY.OS are also not used by anyone besides the IT guys. So we could remove them as well.

Maybe it is a good idea to put old and rarely used entries into a sub menu. This way, they are still accessible to novice users who are generally not familiar with editing config files. I will open an issue for that.

**Pull request merged**
